### ISSUE TITLE
push/check modified base rate on base rate change

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/plugins-wishlist#8]
A plugin that will update all the price labels if a base rate change is detected. Should most likely be carried out within https://github.com/ubiquibot/assistive-pricing if not already there.

[See code reference](https://github.com/ubiquity/ubiquibot/tree/4f15f0f294728e701cb9a2e1aac89e2f73623f31/src/handlers/push)

**Comment by bytegun** [comment]
Can I work on this issue?

**Comment by jordan-ae** [comment]
@Keyrxng Since you've done much of the work already I'll leave it to you then!

**Comment by Keyrxng** [comment]
@jordan-ae thanks buddy I appreciate it

The repo is private as I've had to consistently log env vars in debugging the situation

**Comment by Keyrxng** [comment]
> We can consider making the org config public

That would imply that in order to use secrets like `keys.openAi` it would be strictly through repo secrets, meaning if ever they had to update their API they'd need to update the secret in every repo.

If that is the case, what's the purpose in having properties like `keys.openAi` in the bot config at all if they are just being pulled from the repo meaning that the kernel won't have access to it just the invoked plugin that requires `OPENAI_KEY` as a secret.

Maybe I've missed a step in the direction V2 is taking and I need to read over some issues again but I'm a little confused with this

**Comment by gentlementlegen** [comment]
I am not sure to understand the issue. Each repo should have their own secrets, otherwise we also share secrets on an Org level for things like OPENAI_KEY since it's the same for each repo (only orgs can benefit from these shared secrets). 

Problem passing down these through the config or the settings is that it can be vector for abuse by third parties which we want to avoid.

**Comment by gentlementlegen** [comment]
@Keyrxng something going on here or shall I have a look at it?

**Comment by Keyrxng** [comment]
No issue I can move on this, ty for the follow up.

Just to clarify, if the org config is private we cannot process an org wide update. If there is a public org config we can otherwise it would be on a per-repo config basis.

> We can consider making the org config public, although to me it seems like a lazy answer. I'm sure that we can solve auth via the app for that repository.

I haven't looked into an alternative solution enough to comment on that right now but if @gentlementlegen you have any insight that would be appreciated, I'll have a PR open later today.

**Comment by gentlementlegen** [comment]
@Keyrxng My mistake sorry.

**Comment by Keyrxng** [comment]
@gentlementlegen no worries. I suggested we build a feature so that it auto assigns the author of the merge being merged before we generate the permit it would be so beneficial to avoid this as it happens often

**Comment by gentlementlegen** [comment]
Should be good when we get the disqualifier to work and actually disqualify people, because it will close PRs as well, and the user won't be able to re-assign itself.
